# Домашнее задание к лекции "Функции"

Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов
```
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
```
2. перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)
```
directories = {
    '1': ['2207 876234', '11-2'],
    '2': ['10006'],
    '3': []
}
```

Общие требования к программе:
- код должен быть грамотно декомпозирован (каждая функция отвечает за свою конкретную задачу, дублирующийся функционал переиспользуется, а его код не повторяется);
- в коде отсутствуют глобальные переменные (за исключением **documents** и **directories**);
- пользовательский ввод обрабатывается в цикле **while** до тех пор, пока пользователь явно не завершит программу (вводом команды "**q**").

In [8]:
#перечень всех документов

documents = [
 {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
 {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'},
 {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
#перечень полок, на которых хранятся документы 

directories = {
 '1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': []
}

In [4]:
#Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру

def name():
    user_type = input('Введите номер документа: ')
    name = None
    for document in documents:
        if user_type == document['number']:
            name = document['name'] 
        if user_type != document['number']:
            None
    if name is not None:
        print(f'Владелец документа: {name}')
    if name is None:
        print('Владелец документа не найден')    
name()

Введите номер документа: 4
Владелец документа не найден


In [7]:
#Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится

def shelf():
    user_type = input('Введите номер документа: ')
    shelf = None
    for key, value in directories.items():
        if user_type in value:
            shelf = key
        if user_type != value:
            None
    if shelf is not None:
        print(f'Документ хранится на полке: {shelf}')
    if shelf is None:
        print('Документ не найден в базе')
shelf()

Введите номер документа: 5
Документ не найден в базе


In [9]:
#Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам

def info():
    for document in documents:
        name = document['name']
        t = document['type']
        num = document['number']
        for key, value in directories.items():
            if num in value:
                print(f'№: {num}, тип: {t}, владелец: {name}, полка хранения: {key}')
info()

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


In [15]:
#Пункт 4. Пользователь по команде "ads" может добавить новую полку

def add():
    user_type = input('Введите номер новой полки: ')
    if user_type in directories.keys():
        print('Полка с таким номером уже существует! Текущий перечень полок: ', end='')
        print(*list(directories.keys()), sep=', ')
    else:
        directories[user_type] = []
        print('Полка номер', user_type, 'добавлена. Текущий перечень полок: ', end='')
        print(*list(directories.keys()), sep=', ')
add()

Введите номер новой полки: 10
Полка номер 10 добавлена. Текущий перечень полок: 1, 2, 3, 10


In [16]:
#Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая).

def delete(): 
    user_type = input('Введите номер полки: ')
    if user_type in list(directories.keys()) and directories[user_type] == []:
        del directories[user_type]
        print('Полка удалена. Текущий перечень полок: ', end='')
        print(*list(directories.keys()), sep=', ')
    elif user_type in directories and directories[user_type] != []:
        print('На полке есть документы, удалите их перед удалением полки. Текущий перечень полок: ', end='')
        print(*list(directories.keys()), sep=', ')
    else:
        print('Такой полки не существует. Текущий перечень полок: ', end='')
        print(*list(directories.keys()), sep=', ')
delete()

Введите номер полки: 10
Полка удалена. Текущий перечень полок: 1, 2, 3


In [13]:
#Пункт 1. Пользователь по команде "p" может узнать владельца документа по его номеру
#Пункт 2. Пользователь по команде "s" может по номеру документа узнать на какой полке он хранится
#Пункт 3. Пользователь по команде "l" может увидеть полную информацию по всем документам
#Пункт 4. Пользователь по команде "ads" может добавить новую полку
#Пункт 5. Пользователь по команде "ds" может удалить существующую полку из данных (только если она пустая).

def main():
    while True:
        user_input = input('Введите команду: ')
        if user_input == 'p':
            name()
        elif user_input == 's':
            shelf()
        elif user_input == 'l':
            info()
        elif user_input == 'ads':
            add()
        elif user_input == 'ds':
            delete()
        elif user_input == 'q':
            print('Завершение программы')
            break
        else:
            print('Введена неверная команда')

In [14]:
main()

Введите команду: p
Введите номер документа: 11-2
Владелец документа: Геннадий Покемонов
Введите команду: q
Завершение программы


## Задание 2 (необязательное)

Вам необходимо дополнить программу из задания 1 более продвинутыми командами.

### Пункт 1. Пользователь по команде "*ad*" может добавить новый документ в данные

Примеры работы:

1.

```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
3
```
Результат:  
```
Документ добавлен. Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
№: 42, тип: multipassport, владелец: R2D2, полка хранения: 3
```

2.
```
Введите команду:
ad

Введите номер документа:
42
Введите тип документа:
multipassport
Введите владельца документа:
R2D2
Введите полку для хранения:
4
```
Результат:  
```
Такой полки не существует. Добавьте полку командой as. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 2. Пользователь по команде "*d*" может удалить документ из данных

Примеры работы:

1.

```
Введите команду:
d

Введите номер документа:
10006
```
Результат:  
```
Документ удален. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
```

2.
```
Введите команду:
d

Введите номер документа:
123456
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

### Пункт 3. Пользователь по команде "*m*" может переместить документ с полки на полку

Примеры работы:

1.

```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
3
```
Результат:  
```
Документ перемещен. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

2.
```
Введите команду:
m

Введите номер документа:
11-2
Введите номер полки:
10
```
Результат:  
`Такой полки не существует. Текущий перечень полок: 1, 2, 3.`

3.
```
Введите команду:
m

Введите номер документа:
42
Введите номер полки:
2
```
Результат:  
```
Документ не найден в базе. 
Текущий список документов:
№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2
```

#### ПРИМЕЧАНИЕ
Домашнее задание сдается ссылкой на репозиторий [GitHub](https://github.com/).
Не сможем проверить или помочь, если вы пришлете:
- файлы;
- архивы;
- скриншоты кода.

Все обсуждения и консультации по выполнению домашнего задания ведутся только на соответствующем канале в slack.

##### Как правильно задавать вопросы аспирантам, преподавателям и коллегам
Прежде чем задать вопрос, попробуйте найти ответ в интернете. Навык самостоятельного поиска информации — один из важнейших. Каждый практикующий специалист любого уровня делает это ежедневно.

Сформулируйте вопрос по алгоритму:  
1) Что я делаю?  
2) Какого результата я ожидаю?  
3) Как фактический результат отличается от ожидаемого?  
4) Что я уже попробовал сделать, чтобы исправить проблему?  

По возможности прикрепите к вопросу скриншоты либо ссылки на код. Не выкладывайте все решение, оставляйте только проблемный и воспроизводимый участок кода.